//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.2
//     from Assets/Scripts/Controllers/RtsInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @RtsInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RtsInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RtsInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""7caa1c53-f027-481f-b56d-de1c99ebaea0"",
            ""actions"": [
                {
                    ""name"": ""OnLeftMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""f12e5dbd-58f8-43b9-bc98-cc8b8114989b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OnRightMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""7df8d19e-1cac-40c1-a4e5-cbeb07249148"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""9c5420c1-7280-4746-8d3c-11b9d17865cc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""7c2e1164-d0e2-43f0-a36e-60c3705c970b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMoveUp"",
                    ""type"": ""Button"",
                    ""id"": ""05cf02eb-5112-4a27-afdc-13d2433b4585"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMoveDown"",
                    ""type"": ""Button"",
                    ""id"": ""37eddc1a-4ce2-4816-b0e2-a6cd4ab70143"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectGroup1"",
                    ""type"": ""Button"",
                    ""id"": ""cf3ec541-1bad-4e5f-ac73-ddfd5aede710"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectGroup2"",
                    ""type"": ""Button"",
                    ""id"": ""265c3768-9508-4429-beb2-4467acc6aa96"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectGroup3"",
                    ""type"": ""Button"",
                    ""id"": ""79f97966-417e-4331-98e6-a3f4c580f39e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectGroup4"",
                    ""type"": ""Button"",
                    ""id"": ""bb370946-8160-441b-9676-9afe30b8b863"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeleteActor"",
                    ""type"": ""Button"",
                    ""id"": ""d1986c2f-f924-49da-8822-58d2d9f4bf38"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""84e9393c-6110-44be-8255-8bf4b1aa051e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnLeftMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eec6d60c-d0b3-4fa8-bfd6-aa3794d440b3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OnRightMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2392d634-f388-41a3-b5e0-84d39c18fd73"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cae904d-ebf1-488f-8ddc-4194354b29d9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3eefa3bd-939a-4c69-a1fb-404680f5fe79"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b38bb1e6-9678-4afb-96c9-fea14b0d32a1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72549666-7e67-43b1-a9ea-ff2f6263a01c"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectGroup1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e594df3-dbb0-4def-864c-b49ab1f232ab"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectGroup2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fda12170-d47e-48bc-9cc3-e98e9fc92d23"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectGroup3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25cb50a1-52b5-45b8-98c6-1c29a8b3b1de"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectGroup4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9e0a6bf-fab4-4ad6-94d0-2b3a8bd09303"",
                    ""path"": ""<Keyboard>/delete"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeleteActor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_OnLeftMouseButton = m_Player.FindAction("OnLeftMouseButton", throwIfNotFound: true);
        m_Player_OnRightMouseButton = m_Player.FindAction("OnRightMouseButton", throwIfNotFound: true);
        m_Player_CameraMoveRight = m_Player.FindAction("CameraMoveRight", throwIfNotFound: true);
        m_Player_CameraMoveLeft = m_Player.FindAction("CameraMoveLeft", throwIfNotFound: true);
        m_Player_CameraMoveUp = m_Player.FindAction("CameraMoveUp", throwIfNotFound: true);
        m_Player_CameraMoveDown = m_Player.FindAction("CameraMoveDown", throwIfNotFound: true);
        m_Player_SelectGroup1 = m_Player.FindAction("SelectGroup1", throwIfNotFound: true);
        m_Player_SelectGroup2 = m_Player.FindAction("SelectGroup2", throwIfNotFound: true);
        m_Player_SelectGroup3 = m_Player.FindAction("SelectGroup3", throwIfNotFound: true);
        m_Player_SelectGroup4 = m_Player.FindAction("SelectGroup4", throwIfNotFound: true);
        m_Player_DeleteActor = m_Player.FindAction("DeleteActor", throwIfNotFound: true);
    }

    ~@RtsInput()
    {
        Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, RtsInput.Player.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_OnLeftMouseButton;
    private readonly InputAction m_Player_OnRightMouseButton;
    private readonly InputAction m_Player_CameraMoveRight;
    private readonly InputAction m_Player_CameraMoveLeft;
    private readonly InputAction m_Player_CameraMoveUp;
    private readonly InputAction m_Player_CameraMoveDown;
    private readonly InputAction m_Player_SelectGroup1;
    private readonly InputAction m_Player_SelectGroup2;
    private readonly InputAction m_Player_SelectGroup3;
    private readonly InputAction m_Player_SelectGroup4;
    private readonly InputAction m_Player_DeleteActor;
    public struct PlayerActions
    {
        private @RtsInput m_Wrapper;
        public PlayerActions(@RtsInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @OnLeftMouseButton => m_Wrapper.m_Player_OnLeftMouseButton;
        public InputAction @OnRightMouseButton => m_Wrapper.m_Player_OnRightMouseButton;
        public InputAction @CameraMoveRight => m_Wrapper.m_Player_CameraMoveRight;
        public InputAction @CameraMoveLeft => m_Wrapper.m_Player_CameraMoveLeft;
        public InputAction @CameraMoveUp => m_Wrapper.m_Player_CameraMoveUp;
        public InputAction @CameraMoveDown => m_Wrapper.m_Player_CameraMoveDown;
        public InputAction @SelectGroup1 => m_Wrapper.m_Player_SelectGroup1;
        public InputAction @SelectGroup2 => m_Wrapper.m_Player_SelectGroup2;
        public InputAction @SelectGroup3 => m_Wrapper.m_Player_SelectGroup3;
        public InputAction @SelectGroup4 => m_Wrapper.m_Player_SelectGroup4;
        public InputAction @DeleteActor => m_Wrapper.m_Player_DeleteActor;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @OnLeftMouseButton.started += instance.OnOnLeftMouseButton;
            @OnLeftMouseButton.performed += instance.OnOnLeftMouseButton;
            @OnLeftMouseButton.canceled += instance.OnOnLeftMouseButton;
            @OnRightMouseButton.started += instance.OnOnRightMouseButton;
            @OnRightMouseButton.performed += instance.OnOnRightMouseButton;
            @OnRightMouseButton.canceled += instance.OnOnRightMouseButton;
            @CameraMoveRight.started += instance.OnCameraMoveRight;
            @CameraMoveRight.performed += instance.OnCameraMoveRight;
            @CameraMoveRight.canceled += instance.OnCameraMoveRight;
            @CameraMoveLeft.started += instance.OnCameraMoveLeft;
            @CameraMoveLeft.performed += instance.OnCameraMoveLeft;
            @CameraMoveLeft.canceled += instance.OnCameraMoveLeft;
            @CameraMoveUp.started += instance.OnCameraMoveUp;
            @CameraMoveUp.performed += instance.OnCameraMoveUp;
            @CameraMoveUp.canceled += instance.OnCameraMoveUp;
            @CameraMoveDown.started += instance.OnCameraMoveDown;
            @CameraMoveDown.performed += instance.OnCameraMoveDown;
            @CameraMoveDown.canceled += instance.OnCameraMoveDown;
            @SelectGroup1.started += instance.OnSelectGroup1;
            @SelectGroup1.performed += instance.OnSelectGroup1;
            @SelectGroup1.canceled += instance.OnSelectGroup1;
            @SelectGroup2.started += instance.OnSelectGroup2;
            @SelectGroup2.performed += instance.OnSelectGroup2;
            @SelectGroup2.canceled += instance.OnSelectGroup2;
            @SelectGroup3.started += instance.OnSelectGroup3;
            @SelectGroup3.performed += instance.OnSelectGroup3;
            @SelectGroup3.canceled += instance.OnSelectGroup3;
            @SelectGroup4.started += instance.OnSelectGroup4;
            @SelectGroup4.performed += instance.OnSelectGroup4;
            @SelectGroup4.canceled += instance.OnSelectGroup4;
            @DeleteActor.started += instance.OnDeleteActor;
            @DeleteActor.performed += instance.OnDeleteActor;
            @DeleteActor.canceled += instance.OnDeleteActor;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @OnLeftMouseButton.started -= instance.OnOnLeftMouseButton;
            @OnLeftMouseButton.performed -= instance.OnOnLeftMouseButton;
            @OnLeftMouseButton.canceled -= instance.OnOnLeftMouseButton;
            @OnRightMouseButton.started -= instance.OnOnRightMouseButton;
            @OnRightMouseButton.performed -= instance.OnOnRightMouseButton;
            @OnRightMouseButton.canceled -= instance.OnOnRightMouseButton;
            @CameraMoveRight.started -= instance.OnCameraMoveRight;
            @CameraMoveRight.performed -= instance.OnCameraMoveRight;
            @CameraMoveRight.canceled -= instance.OnCameraMoveRight;
            @CameraMoveLeft.started -= instance.OnCameraMoveLeft;
            @CameraMoveLeft.performed -= instance.OnCameraMoveLeft;
            @CameraMoveLeft.canceled -= instance.OnCameraMoveLeft;
            @CameraMoveUp.started -= instance.OnCameraMoveUp;
            @CameraMoveUp.performed -= instance.OnCameraMoveUp;
            @CameraMoveUp.canceled -= instance.OnCameraMoveUp;
            @CameraMoveDown.started -= instance.OnCameraMoveDown;
            @CameraMoveDown.performed -= instance.OnCameraMoveDown;
            @CameraMoveDown.canceled -= instance.OnCameraMoveDown;
            @SelectGroup1.started -= instance.OnSelectGroup1;
            @SelectGroup1.performed -= instance.OnSelectGroup1;
            @SelectGroup1.canceled -= instance.OnSelectGroup1;
            @SelectGroup2.started -= instance.OnSelectGroup2;
            @SelectGroup2.performed -= instance.OnSelectGroup2;
            @SelectGroup2.canceled -= instance.OnSelectGroup2;
            @SelectGroup3.started -= instance.OnSelectGroup3;
            @SelectGroup3.performed -= instance.OnSelectGroup3;
            @SelectGroup3.canceled -= instance.OnSelectGroup3;
            @SelectGroup4.started -= instance.OnSelectGroup4;
            @SelectGroup4.performed -= instance.OnSelectGroup4;
            @SelectGroup4.canceled -= instance.OnSelectGroup4;
            @DeleteActor.started -= instance.OnDeleteActor;
            @DeleteActor.performed -= instance.OnDeleteActor;
            @DeleteActor.canceled -= instance.OnDeleteActor;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnOnLeftMouseButton(InputAction.CallbackContext context);
        void OnOnRightMouseButton(InputAction.CallbackContext context);
        void OnCameraMoveRight(InputAction.CallbackContext context);
        void OnCameraMoveLeft(InputAction.CallbackContext context);
        void OnCameraMoveUp(InputAction.CallbackContext context);
        void OnCameraMoveDown(InputAction.CallbackContext context);
        void OnSelectGroup1(InputAction.CallbackContext context);
        void OnSelectGroup2(InputAction.CallbackContext context);
        void OnSelectGroup3(InputAction.CallbackContext context);
        void OnSelectGroup4(InputAction.CallbackContext context);
        void OnDeleteActor(InputAction.CallbackContext context);
    }
}
